import { Artist, Artwork } from "./types";

export const artists: Artist[] = [
  {
    id: "1",
    name: "Olumide Osamede",
    nationality: "Nigerian",
    birthYear: 1995,
    bio: "Olumide Osamede is a contemporary Nigerian artist known for his vibrant use of color and exploration of cultural identity. His work often features bold geometric patterns that reflect the intersection of traditional African art and modern abstraction. Born in Lagos, Osamede studied fine arts at the University of Lagos before gaining international recognition for his unique visual language.",
    imageUrl: "/images/artists/olumide-osamede.jpg",
    featured: true,
  },
  {
    id: "2",
    name: "Amara Chen",
    nationality: "Taiwanese",
    birthYear: 1988,
    bio: "Amara Chen creates contemplative landscapes that blur the boundaries between reality and imagination. Her ethereal oil paintings capture fleeting moments of natural beauty with masterful technique.",
    imageUrl: "/images/artists/amara-chen.jpg",
    featured: false,
  },
  {
    id: "3",
    name: "Marcus Weber",
    nationality: "German",
    birthYear: 1992,
    bio: "Marcus Weber is a mixed-media artist whose work explores the relationship between urban environments and human emotion. His layered compositions combine photography, painting, and digital elements.",
    imageUrl: "/images/artists/marcus-weber.jpg",
    featured: false,
  },
  {
    id: "4",
    name: "Sofia Ramirez",
    nationality: "Mexican",
    birthYear: 1990,
    bio: "Sofia Ramirez creates powerful portraits that celebrate the strength and resilience of women. Her bold use of color and texture brings her subjects to life with remarkable intensity.",
    imageUrl: "/images/artists/sofia-ramirez.jpg",
    featured: false,
  },
  {
    id: "5",
    name: "Yuki Tanaka",
    nationality: "Japanese",
    birthYear: 1985,
    bio: "Yuki Tanaka is known for minimalist compositions that explore the concept of negative space. Her work draws inspiration from Zen philosophy and traditional Japanese aesthetics.",
    imageUrl: "/images/artists/yuki-tanaka.jpg",
    featured: false,
  },
  {
    id: "6",
    name: "Kwame Asante",
    nationality: "Ghanaian",
    birthYear: 1982,
    bio: "Kwame Asante's abstract expressionist works explore themes of identity, migration, and the African diaspora. His large-scale canvases feature energetic brushwork and layered symbolism.",
    imageUrl: "/images/artists/kwame-asante.jpg",
    featured: true,
  },
  {
    id: "7",
    name: "Isabella Rossi",
    nationality: "Italian",
    birthYear: 1987,
    bio: "Isabella Rossi creates intricate sculptures from reclaimed materials, exploring the relationship between industrial waste and natural forms. Her work has been exhibited across Europe.",
    imageUrl: "/images/artists/isabella-rossi.jpg",
    featured: false,
  },
  {
    id: "8",
    name: "Lars Jensen",
    nationality: "Danish",
    birthYear: 1979,
    bio: "Lars Jensen's photographic series document climate change in the Arctic Circle. His stark, beautiful images raise awareness about environmental issues while celebrating natural beauty.",
    imageUrl: "/images/artists/lars-jensen.jpg",
    featured: false,
  },
  {
    id: "9",
    name: "Aisha Hassan",
    nationality: "Egyptian",
    birthYear: 1993,
    bio: "Aisha Hassan combines traditional Islamic geometric patterns with contemporary digital art. Her vibrant installations have transformed public spaces across the Middle East.",
    imageUrl: "/images/artists/aisha-hassan.jpg",
    featured: true,
  },
  {
    id: "10",
    name: "Mateo Cruz",
    nationality: "Colombian",
    birthYear: 1984,
    bio: "Mateo Cruz's mixed-media works explore indigenous Colombian traditions through a modern lens. His colorful assemblages incorporate natural materials and found objects.",
    imageUrl: "/images/artists/mateo-cruz.jpg",
    featured: false,
  },
  {
    id: "11",
    name: "Nina Petrova",
    nationality: "Russian",
    birthYear: 1976,
    bio: "Nina Petrova creates monumental oil paintings that depict historical narratives with contemporary relevance. Her detailed compositions often feature hundreds of figures.",
    imageUrl: "/images/artists/nina-petrova.jpg",
    featured: false,
  },
  {
    id: "12",
    name: "Kaito Nakamura",
    nationality: "Japanese",
    birthYear: 1990,
    bio: "Kaito Nakamura merges traditional Japanese ink painting techniques with augmented reality. Viewers can use smartphones to see his artworks come to life with animation.",
    imageUrl: "/images/artists/kaito-nakamura.jpg",
    featured: false,
  },
  {
    id: "13",
    name: "Fatima Al-Mansoori",
    nationality: "Emirati",
    birthYear: 1988,
    bio: "Fatima Al-Mansoori creates delicate glass sculptures that explore themes of memory and cultural preservation. Her work references traditional Arabic architecture and design.",
    imageUrl: "/images/artists/fatima-al-mansoori.jpg",
    featured: true,
  },
  {
    id: "14",
    name: "Oliver Schmidt",
    nationality: "Austrian",
    birthYear: 1981,
    bio: "Oliver Schmidt's kinetic sculptures use wind, water, and light to create constantly changing installations. His work explores the intersection of art and physics.",
    imageUrl: "/images/artists/oliver-schmidt.jpg",
    featured: false,
  },
  {
    id: "15",
    name: "Priya Sharma",
    nationality: "Indian",
    birthYear: 1991,
    bio: "Priya Sharma creates intricate textile works that combine traditional Indian embroidery techniques with contemporary storytelling. Her pieces often address social issues.",
    imageUrl: "/images/artists/priya-sharma.jpg",
    featured: false,
  },
  {
    id: "16",
    name: "Carlos Mendez",
    nationality: "Argentinian",
    birthYear: 1978,
    bio: "Carlos Mendez paints hyper-realistic urban scenes that capture the poetry of everyday life in Buenos Aires. His work has been described as magical realism in visual form.",
    imageUrl: "/images/artists/carlos-mendez.jpg",
    featured: false,
  },
  {
    id: "17",
    name: "Zahra Bahrami",
    nationality: "Iranian",
    birthYear: 1985,
    bio: "Zahra Bahrami creates miniature paintings on unconventional surfaces, exploring themes of confinement and freedom in contemporary Iranian society.",
    imageUrl: "/images/artists/zahra-bahrami.jpg",
    featured: false,
  },
  {
    id: "18",
    name: "Thomas O'Connell",
    nationality: "Irish",
    birthYear: 1975,
    bio: "Thomas O'Connell's landscape paintings capture the dramatic weather and light of the Irish coastline. His work has been collected by major museums across Europe.",
    imageUrl: "/images/artists/thomas-oconnell.jpg",
    featured: true,
  },
  {
    id: "19",
    name: "Lena Vogel",
    nationality: "Swiss",
    birthYear: 1992,
    bio: "Lena Vogel creates immersive sound installations that explore human perception and the natural world. Her work has been featured in major art biennials worldwide.",
    imageUrl: "/images/artists/lena-vogel.jpg",
    featured: false,
  },
  {
    id: "20",
    name: "Rafael Silva",
    nationality: "Brazilian",
    birthYear: 1983,
    bio: "Rafael Silva's vibrant street art has transformed neighborhoods across São Paulo. His work addresses themes of social justice and community empowerment.",
    imageUrl: "/images/artists/rafael-silva.jpg",
    featured: false,
  },
  {
    id: "21",
    name: "Chloe Dubois",
    nationality: "French",
    birthYear: 1989,
    bio: "Chloe Dubois creates large-scale ceramic installations that explore themes of fragility and resilience. Her work references both ancient pottery techniques and modern design.",
    imageUrl: "/images/artists/chloe-dubois.jpg",
    featured: false,
  },
  {
    id: "22",
    name: "David Park",
    nationality: "Korean-American",
    birthYear: 1990,
    bio: "David Park's digital animations explore the intersection of technology and human emotion. His work has been featured in film festivals and art galleries worldwide.",
    imageUrl: "/images/artists/david-park.jpg",
    featured: false,
  },
  {
    id: "23",
    name: "Maya Singh",
    nationality: "Indian-Canadian",
    birthYear: 1986,
    bio: "Maya Singh creates mixed-media works that explore diaspora identity and cultural hybridity. Her installations incorporate video, photography, and found objects.",
    imageUrl: "/images/artists/maya-singh.jpg",
    featured: false,
  },
  {
    id: "24",
    name: "Viktor Ivanov",
    nationality: "Ukrainian",
    birthYear: 1977,
    bio: "Viktor Ivanov creates monumental steel sculptures that explore industrial aesthetics and human resilience. His work often references Ukrainian history and folklore.",
    imageUrl: "/images/artists/viktor-ivanov.jpg",
    featured: true,
  },
  {
    id: "25",
    name: "Sophie Williams",
    nationality: "Australian",
    birthYear: 1994,
    bio: "Sophie Williams creates eco-art installations using natural materials that change and decay over time. Her work explores sustainability and our relationship with nature.",
    imageUrl: "/images/artists/sophie-williams.jpg",
    featured: false,
  },
  {
    id: "26",
    name: "Kenji Yamamoto",
    nationality: "Japanese",
    birthYear: 1980,
    bio: "Kenji Yamamoto creates minimalist light installations that transform architectural spaces. His work explores perception and the phenomenology of light.",
    imageUrl: "/images/artists/kenji-yamamoto.jpg",
    featured: false,
  },
  {
    id: "27",
    name: "Ana Costa",
    nationality: "Portuguese",
    birthYear: 1988,
    bio: "Ana Costa paints atmospheric seascapes that capture the power and mystery of the Atlantic Ocean. Her work is informed by Portugal's maritime history.",
    imageUrl: "/images/artists/ana-costa.jpg",
    featured: false,
  },
  {
    id: "28",
    name: "Mohammed Al-Farsi",
    nationality: "Saudi Arabian",
    birthYear: 1983,
    bio: "Mohammed Al-Farsi creates calligraphic works that blend traditional Arabic script with contemporary abstract painting. His work explores language as visual art.",
    imageUrl: "/images/artists/mohammed-al-farsi.jpg",
    featured: true,
  },
  {
    id: "29",
    name: "Elena Popescu",
    nationality: "Romanian",
    birthYear: 1979,
    bio: "Elena Popescu creates intricate paper-cut artworks that explore Romanian folklore and mythology. Her delicate works require hundreds of hours of meticulous cutting.",
    imageUrl: "/images/artists/elena-popescu.jpg",
    featured: false,
  },
  {
    id: "30",
    name: "Benjamin Taylor",
    nationality: "American",
    birthYear: 1991,
    bio: "Benjamin Taylor creates hyper-realistic portraits that explore identity in the digital age. His paintings often incorporate elements of glitch art and digital distortion.",
    imageUrl: "/images/artists/benjamin-taylor.jpg",
    featured: false,
  },
];

export const artworks: Artwork[] = [
  {
    id: "1",
    title: "Green Artwork",
    artistId: "1",
    artistName: "Olumide Osamede",
    year: 2020,
    medium: "Oil on canvas",
    dimensions: { width: 24, height: 24, unit: "in" },
    price: 1500,
    currency: "€",
    imageUrl: "/images/artworks/green-artwork.jpg",
    description:
      "A vibrant exploration of organic forms and natural color palettes.",
    available: true,
    featured: true,
  },
  {
    id: "2",
    title: "Superimposed Roots",
    artistId: "1",
    artistName: "Olumide Osamede",
    year: 2021,
    medium: "Mixed media on canvas",
    dimensions: { width: 36, height: 48, unit: "in" },
    price: 2800,
    currency: "€",
    imageUrl: "/images/artworks/superimposed-roots.jpg",
    description:
      "An intricate layering of cultural heritage and modern identity.",
    available: true,
    featured: true,
  },
  {
    id: "3",
    title: "Urban Meditation",
    artistId: "3",
    artistName: "Marcus Weber",
    year: 2022,
    medium: "Mixed media",
    dimensions: { width: 30, height: 40, unit: "in" },
    price: 2200,
    currency: "€",
    imageUrl: "/images/artworks/urban-meditation.jpg",
    description:
      "A contemplative piece capturing quiet moments in bustling city life.",
    available: true,
    featured: false,
  },
  {
    id: "4",
    title: "Essence of Strength",
    artistId: "4",
    artistName: "Sofia Ramirez",
    year: 2023,
    medium: "Acrylic on canvas",
    dimensions: { width: 32, height: 44, unit: "in" },
    price: 1900,
    currency: "€",
    imageUrl: "/images/artworks/essence-of-strength.jpg",
    description: "A powerful portrait celebrating feminine resilience.",
    available: true,
    featured: false,
  },
  {
    id: "5",
    title: "Tranquil Waters",
    artistId: "2",
    artistName: "Amara Chen",
    year: 2021,
    medium: "Oil on canvas",
    dimensions: { width: 28, height: 36, unit: "in" },
    price: 1700,
    currency: "€",
    imageUrl: "/images/artworks/tranquil-waters.jpg",
    description:
      "An ethereal landscape that captures the serene beauty of water.",
    available: true,
    featured: false,
  },
  {
    id: "6",
    title: "Void and Form",
    artistId: "5",
    artistName: "Yuki Tanaka",
    year: 2022,
    medium: "Ink on paper",
    dimensions: { width: 20, height: 26, unit: "in" },
    price: 1200,
    currency: "€",
    imageUrl: "/images/artworks/void-and-form.jpg",
    description: "A minimalist exploration of space and emptiness.",
    available: true,
    featured: false,
  },
  {
    id: "7",
    title: "Cultural Tapestry",
    artistId: "1",
    artistName: "Olumide Osamede",
    year: 2023,
    medium: "Oil on canvas",
    dimensions: { width: 40, height: 50, unit: "in" },
    price: 3200,
    currency: "€",
    imageUrl: "/images/artworks/cultural-tapestry.jpg",
    description:
      "A complex weaving of patterns representing diverse narratives.",
    available: true,
    featured: false,
  },
  {
    id: "8",
    title: "Sunset Reverie",
    artistId: "2",
    artistName: "Amara Chen",
    year: 2020,
    medium: "Oil on canvas",
    dimensions: { width: 34, height: 46, unit: "in" },
    price: 1850,
    currency: "€",
    imageUrl: "/images/artworks/sunset-reverie.jpg",
    description: "A dreamlike interpretation of twilight with glowing hues.",
    available: false,
    featured: false,
  },
  // Additional artworks
  {
    id: "9",
    title: "Golden Horizons",
    artistId: "6",
    artistName: "Kwame Asante",
    year: 2022,
    medium: "Acrylic and gold leaf on canvas",
    dimensions: { width: 48, height: 60, unit: "in" },
    price: 4500,
    currency: "€",
    imageUrl: "/images/artworks/golden-horizons.jpg",
    description: "An abstract exploration of migration and new beginnings.",
    available: true,
    featured: true,
  },
  {
    id: "10",
    title: "Metamorphosis",
    artistId: "7",
    artistName: "Isabella Rossi",
    year: 2021,
    medium: "Reclaimed steel and copper",
    dimensions: { width: 72, height: 48, unit: "in" },
    price: 6800,
    currency: "€",
    imageUrl: "/images/artworks/metamorphosis.jpg",
    description:
      "A sculpture exploring transformation from industrial to organic forms.",
    available: true,
    featured: false,
  },
  {
    id: "11",
    title: "Arctic Silence",
    artistId: "8",
    artistName: "Lars Jensen",
    year: 2023,
    medium: "Archival pigment print",
    dimensions: { width: 40, height: 30, unit: "in" },
    price: 2200,
    currency: "€",
    imageUrl: "/images/artworks/arctic-silence.jpg",
    description:
      "A breathtaking photograph of melting glaciers under midnight sun.",
    available: true,
    featured: true,
  },
  {
    id: "12",
    title: "Geometric Harmony",
    artistId: "9",
    artistName: "Aisha Hassan",
    year: 2022,
    medium: "Digital art on aluminum",
    dimensions: { width: 36, height: 36, unit: "in" },
    price: 3200,
    currency: "€",
    imageUrl: "/images/artworks/geometric-harmony.jpg",
    description:
      "A vibrant fusion of Islamic geometry and contemporary design.",
    available: true,
    featured: false,
  },
  {
    id: "13",
    title: "Amazon Dreams",
    artistId: "10",
    artistName: "Mateo Cruz",
    year: 2023,
    medium: "Mixed media assemblage",
    dimensions: { width: 42, height: 54, unit: "in" },
    price: 3800,
    currency: "€",
    imageUrl: "/images/artworks/amazon-dreams.jpg",
    description:
      "An immersive work incorporating natural materials from the Colombian rainforest.",
    available: true,
    featured: false,
  },
  {
    id: "14",
    title: "Winter Palace",
    artistId: "11",
    artistName: "Nina Petrova",
    year: 2021,
    medium: "Oil on canvas",
    dimensions: { width: 60, height: 84, unit: "in" },
    price: 12500,
    currency: "€",
    imageUrl: "/images/artworks/winter-palace.jpg",
    description:
      "A monumental historical narrative painting with hundreds of figures.",
    available: true,
    featured: true,
  },
  {
    id: "15",
    title: "Digital Zen Garden",
    artistId: "12",
    artistName: "Kaito Nakamura",
    year: 2023,
    medium: "Ink and augmented reality",
    dimensions: { width: 24, height: 18, unit: "in" },
    price: 2800,
    currency: "€",
    imageUrl: "/images/artworks/digital-zen-garden.jpg",
    description:
      "Traditional ink painting that comes to life with AR technology.",
    available: true,
    featured: false,
  },
  {
    id: "16",
    title: "Desert Rose",
    artistId: "13",
    artistName: "Fatima Al-Mansoori",
    year: 2022,
    medium: "Blown glass and steel",
    dimensions: { width: 24, height: 36, unit: "in" },
    price: 4200,
    currency: "€",
    imageUrl: "/images/artworks/desert-rose.jpg",
    description:
      "A delicate glass sculpture inspired by traditional Arabic architecture.",
    available: true,
    featured: false,
  },
  {
    id: "17",
    title: "Wind Choreography",
    artistId: "14",
    artistName: "Oliver Schmidt",
    year: 2023,
    medium: "Kinetic sculpture",
    dimensions: { width: 96, height: 96, unit: "in" },
    price: 15000,
    currency: "€",
    imageUrl: "/images/artworks/wind-choreography.jpg",
    description:
      "A large-scale kinetic installation that moves with natural wind patterns.",
    available: false,
    featured: true,
  },
  {
    id: "18",
    title: "Threads of Memory",
    artistId: "15",
    artistName: "Priya Sharma",
    year: 2022,
    medium: "Embroidery on silk",
    dimensions: { width: 48, height: 36, unit: "in" },
    price: 3200,
    currency: "€",
    imageUrl: "/images/artworks/threads-of-memory.jpg",
    description:
      "Intricate textile work exploring family history through traditional embroidery.",
    available: true,
    featured: false,
  },
  {
    id: "19",
    title: "Buenos Aires Nocturne",
    artistId: "16",
    artistName: "Carlos Mendez",
    year: 2023,
    medium: "Oil on canvas",
    dimensions: { width: 40, height: 30, unit: "in" },
    price: 3800,
    currency: "€",
    imageUrl: "/images/artworks/buenos-aires-nocturne.jpg",
    description: "Hyper-realistic painting of a rainy night in Buenos Aires.",
    available: true,
    featured: false,
  },
  {
    id: "20",
    title: "Whispering Walls",
    artistId: "17",
    artistName: "Zahra Bahrami",
    year: 2021,
    medium: "Miniature on ceramic",
    dimensions: { width: 8, height: 8, unit: "in" },
    price: 1800,
    currency: "€",
    imageUrl: "/images/artworks/whispering-walls.jpg",
    description:
      "Intricate miniature painting exploring themes of confinement.",
    available: true,
    featured: false,
  },
  {
    id: "21",
    title: "Cliffs of Moher",
    artistId: "18",
    artistName: "Thomas O'Connell",
    year: 2022,
    medium: "Oil on canvas",
    dimensions: { width: 48, height: 36, unit: "in" },
    price: 4200,
    currency: "€",
    imageUrl: "/images/artworks/cliffs-of-moher.jpg",
    description:
      "Dramatic seascape capturing the raw power of the Irish coastline.",
    available: true,
    featured: true,
  },
  {
    id: "22",
    title: "Forest Symphony",
    artistId: "19",
    artistName: "Lena Vogel",
    year: 2023,
    medium: "Sound installation",
    dimensions: { width: 120, height: 120, unit: "in" },
    price: 8500,
    currency: "€",
    imageUrl: "/images/artworks/forest-symphony.jpg",
    description: "Immersive sound installation recreating a forest soundscape.",
    available: true,
    featured: false,
  },
  {
    id: "23",
    title: "Urban Bloom",
    artistId: "20",
    artistName: "Rafael Silva",
    year: 2022,
    medium: "Spray paint on concrete",
    dimensions: { width: 144, height: 96, unit: "in" },
    price: 6800,
    currency: "€",
    imageUrl: "/images/artworks/urban-bloom.jpg",
    description:
      "Large-scale street art mural celebrating community resilience.",
    available: false,
    featured: true,
  },
  {
    id: "24",
    title: "Fragile Balance",
    artistId: "21",
    artistName: "Chloe Dubois",
    year: 2023,
    medium: "Ceramic installation",
    dimensions: { width: 72, height: 48, unit: "in" },
    price: 5200,
    currency: "€",
    imageUrl: "/images/artworks/fragile-balance.jpg",
    description:
      "Ceramic sculpture exploring the delicate balance of ecosystems.",
    available: true,
    featured: false,
  },
  {
    id: "25",
    title: "Digital Emotions",
    artistId: "22",
    artistName: "David Park",
    year: 2022,
    medium: "Digital animation",
    dimensions: { width: 1920, height: 1080, unit: "px" },
    price: 2800,
    currency: "€",
    imageUrl: "/images/artworks/digital-emotions.jpg",
    description: "Animated exploration of human emotions in the digital age.",
    available: true,
    featured: false,
  },
  {
    id: "26",
    title: "Between Worlds",
    artistId: "23",
    artistName: "Maya Singh",
    year: 2023,
    medium: "Mixed media installation",
    dimensions: { width: 96, height: 72, unit: "in" },
    price: 4500,
    currency: "€",
    imageUrl: "/images/artworks/between-worlds.jpg",
    description:
      "Installation exploring cultural hybridity and diaspora identity.",
    available: true,
    featured: true,
  },
  {
    id: "27",
    title: "Steel Memory",
    artistId: "24",
    artistName: "Viktor Ivanov",
    year: 2021,
    medium: "Steel sculpture",
    dimensions: { width: 84, height: 60, unit: "in" },
    price: 9800,
    currency: "€",
    imageUrl: "/images/artworks/steel-memory.jpg",
    description:
      "Monumental steel sculpture referencing Ukrainian historical resilience.",
    available: true,
    featured: false,
  },
  {
    id: "28",
    title: "Temporal Layers",
    artistId: "25",
    artistName: "Sophie Williams",
    year: 2023,
    medium: "Natural materials installation",
    dimensions: { width: 120, height: 96, unit: "in" },
    price: 3200,
    currency: "€",
    imageUrl: "/images/artworks/temporal-layers.jpg",
    description: "Eco-art installation that changes naturally over time.",
    available: true,
    featured: false,
  },
  {
    id: "29",
    title: "Light Meditation",
    artistId: "26",
    artistName: "Kenji Yamamoto",
    year: 2022,
    medium: "LED light installation",
    dimensions: { width: 96, height: 96, unit: "in" },
    price: 6500,
    currency: "€",
    imageUrl: "/images/artworks/light-meditation.jpg",
    description: "Minimalist light installation creating meditative spaces.",
    available: true,
    featured: true,
  },
  {
    id: "30",
    title: "Atlantic Majesty",
    artistId: "27",
    artistName: "Ana Costa",
    year: 2023,
    medium: "Oil on canvas",
    dimensions: { width: 48, height: 36, unit: "in" },
    price: 3800,
    currency: "€",
    imageUrl: "/images/artworks/atlantic-majesty.jpg",
    description: "Powerful seascape capturing the Atlantic Ocean's majesty.",
    available: true,
    featured: false,
  },
  {
    id: "31",
    title: "Calligraphic Flow",
    artistId: "28",
    artistName: "Mohammed Al-Farsi",
    year: 2022,
    medium: "Acrylic and ink on canvas",
    dimensions: { width: 60, height: 40, unit: "in" },
    price: 4200,
    currency: "€",
    imageUrl: "/images/artworks/calligraphic-flow.jpg",
    description:
      "Abstract calligraphy blending traditional Arabic script with modern painting.",
    available: true,
    featured: false,
  },
  {
    id: "32",
    title: "Forest Spirits",
    artistId: "29",
    artistName: "Elena Popescu",
    year: 2021,
    medium: "Paper cut art",
    dimensions: { width: 36, height: 24, unit: "in" },
    price: 2800,
    currency: "€",
    imageUrl: "/images/artworks/forest-spirits.jpg",
    description:
      "Intricate paper cut artwork exploring Romanian forest mythology.",
    available: true,
    featured: true,
  },
  {
    id: "33",
    title: "Digital Self",
    artistId: "30",
    artistName: "Benjamin Taylor",
    year: 2023,
    medium: "Oil on canvas",
    dimensions: { width: 40, height: 30, unit: "in" },
    price: 3500,
    currency: "€",
    imageUrl: "/images/artworks/digital-self.jpg",
    description: "Hyper-realistic portrait with digital distortion elements.",
    available: true,
    featured: false,
  },
  // Additional artworks from original artists
  {
    id: "34",
    title: "Rhythmic Patterns",
    artistId: "1",
    artistName: "Olumide Osamede",
    year: 2022,
    medium: "Mixed media on wood",
    dimensions: { width: 36, height: 36, unit: "in" },
    price: 2900,
    currency: "€",
    imageUrl: "/images/artworks/rhythmic-patterns.jpg",
    description: "Geometric exploration of cultural rhythms and patterns.",
    available: true,
    featured: false,
  },
  {
    id: "35",
    title: "Mountain Mist",
    artistId: "2",
    artistName: "Amara Chen",
    year: 2023,
    medium: "Oil on canvas",
    dimensions: { width: 42, height: 54, unit: "in" },
    price: 3200,
    currency: "€",
    imageUrl: "/images/artworks/mountain-mist.jpg",
    description: "Atmospheric landscape of mist-shrouded Taiwanese mountains.",
    available: true,
    featured: true,
  },
  {
    id: "36",
    title: "Neon Dreams",
    artistId: "3",
    artistName: "Marcus Weber",
    year: 2023,
    medium: "Mixed media with neon",
    dimensions: { width: 48, height: 36, unit: "in" },
    price: 3800,
    currency: "€",
    imageUrl: "/images/artworks/neon-dreams.jpg",
    description:
      "Urban nightscape incorporating actual neon lighting elements.",
    available: true,
    featured: false,
  },
  {
    id: "37",
    title: "Generations",
    artistId: "4",
    artistName: "Sofia Ramirez",
    year: 2022,
    medium: "Oil on canvas",
    dimensions: { width: 60, height: 48, unit: "in" },
    price: 4500,
    currency: "€",
    imageUrl: "/images/artworks/generations.jpg",
    description: "Multi-generational portrait celebrating family and heritage.",
    available: false,
    featured: true,
  },
  {
    id: "38",
    title: "Empty Space",
    artistId: "5",
    artistName: "Yuki Tanaka",
    year: 2023,
    medium: "Ink on silk",
    dimensions: { width: 30, height: 40, unit: "in" },
    price: 2400,
    currency: "€",
    imageUrl: "/images/artworks/empty-space.jpg",
    description:
      "Minimalist work exploring the concept of ma (negative space).",
    available: true,
    featured: false,
  },
  // More artworks from new artists
  {
    id: "39",
    title: "Diaspora Dreams",
    artistId: "6",
    artistName: "Kwame Asante",
    year: 2023,
    medium: "Mixed media on canvas",
    dimensions: { width: 54, height: 72, unit: "in" },
    price: 5800,
    currency: "€",
    imageUrl: "/images/artworks/diaspora-dreams.jpg",
    description:
      "Large-scale abstract work exploring the African diaspora experience.",
    available: true,
    featured: false,
  },
  {
    id: "40",
    title: "Industrial Bloom",
    artistId: "7",
    artistName: "Isabella Rossi",
    year: 2022,
    medium: "Reclaimed industrial materials",
    dimensions: { width: 60, height: 84, unit: "in" },
    price: 7500,
    currency: "€",
    imageUrl: "/images/artworks/industrial-bloom.jpg",
    description:
      "Sculpture made from discarded machine parts transformed into floral forms.",
    available: true,
    featured: true,
  },
  {
    id: "41",
    title: "Melting Memories",
    artistId: "8",
    artistName: "Lars Jensen",
    year: 2023,
    medium: "Photographic diptych",
    dimensions: { width: 60, height: 40, unit: "in" },
    price: 3200,
    currency: "€",
    imageUrl: "/images/artworks/melting-memories.jpg",
    description: "Contrasting images showing Arctic ice loss over decades.",
    available: true,
    featured: false,
  },
  {
    id: "42",
    title: "Digital Mosque",
    artistId: "9",
    artistName: "Aisha Hassan",
    year: 2023,
    medium: "Digital projection mapping",
    dimensions: { width: 240, height: 180, unit: "in" },
    price: 12500,
    currency: "€",
    imageUrl: "/images/artworks/digital-mosque.jpg",
    description: "Large-scale projection mapping on architectural surfaces.",
    available: true,
    featured: true,
  },
  {
    id: "43",
    title: "Andean Spirit",
    artistId: "10",
    artistName: "Mateo Cruz",
    year: 2022,
    medium: "Mixed media with natural fibers",
    dimensions: { width: 48, height: 60, unit: "in" },
    price: 4200,
    currency: "€",
    imageUrl: "/images/artworks/andean-spirit.jpg",
    description: "Colorful assemblage celebrating Andean cultural traditions.",
    available: true,
    featured: false,
  },
  {
    id: "44",
    title: "Revolutionary Dawn",
    artistId: "11",
    artistName: "Nina Petrova",
    year: 2022,
    medium: "Oil on canvas",
    dimensions: { width: 72, height: 96, unit: "in" },
    price: 15800,
    currency: "€",
    imageUrl: "/images/artworks/revolutionary-dawn.jpg",
    description:
      "Historical narrative painting depicting a pivotal moment in Russian history.",
    available: false,
    featured: true,
  },
  {
    id: "45",
    title: "Ink and Code",
    artistId: "12",
    artistName: "Kaito Nakamura",
    year: 2023,
    medium: "Interactive digital art",
    dimensions: { width: 1920, height: 1080, unit: "px" },
    price: 3500,
    currency: "€",
    imageUrl: "/images/artworks/ink-and-code.jpg",
    description:
      "Interactive artwork blending traditional sumi-e ink painting with coding.",
    available: true,
    featured: false,
  },
  {
    id: "46",
    title: "Oasis",
    artistId: "13",
    artistName: "Fatima Al-Mansoori",
    year: 2023,
    medium: "Glass and light installation",
    dimensions: { width: 36, height: 48, unit: "in" },
    price: 5200,
    currency: "€",
    imageUrl: "/images/artworks/oasis.jpg",
    description:
      "Glass sculpture that refracts light to create oasis-like patterns.",
    available: true,
    featured: true,
  },
  {
    id: "47",
    title: "Solar Dance",
    artistId: "14",
    artistName: "Oliver Schmidt",
    year: 2022,
    medium: "Solar-powered kinetic sculpture",
    dimensions: { width: 84, height: 84, unit: "in" },
    price: 16800,
    currency: "€",
    imageUrl: "/images/artworks/solar-dance.jpg",
    description:
      "Kinetic sculpture powered by sunlight, creating hypnotic movements.",
    available: true,
    featured: false,
  },
  {
    id: "48",
    title: "Women's Work",
    artistId: "15",
    artistName: "Priya Sharma",
    year: 2023,
    medium: "Textile and embroidery",
    dimensions: { width: 60, height: 48, unit: "in" },
    price: 4200,
    currency: "€",
    imageUrl: "/images/artworks/womens-work.jpg",
    description:
      "Textile work celebrating women's labor and creativity across generations.",
    available: true,
    featured: true,
  },
  {
    id: "49",
    title: "Tango Night",
    artistId: "16",
    artistName: "Carlos Mendez",
    year: 2022,
    medium: "Oil on canvas",
    dimensions: { width: 48, height: 36, unit: "in" },
    price: 4200,
    currency: "€",
    imageUrl: "/images/artworks/tango-night.jpg",
    description: "Vibrant scene of tango dancers in a Buenos Aires milonga.",
    available: true,
    featured: false,
  },
  {
    id: "50",
    title: "Hidden Voices",
    artistId: "17",
    artistName: "Zahra Bahrami",
    year: 2023,
    medium: "Miniature on parchment",
    dimensions: { width: 6, height: 8, unit: "in" },
    price: 2200,
    currency: "€",
    imageUrl: "/images/artworks/hidden-voices.jpg",
    description:
      "Exquisite miniature exploring themes of censorship and expression.",
    available: true,
    featured: false,
  },
  // Adding even more to reach 75+ artworks
  {
    id: "51",
    title: "Celtic Storm",
    artistId: "18",
    artistName: "Thomas O'Connell",
    year: 2023,
    medium: "Oil on canvas",
    dimensions: { width: 54, height: 42, unit: "in" },
    price: 4800,
    currency: "€",
    imageUrl: "/images/artworks/celtic-storm.jpg",
    description: "Dramatic painting of a storm approaching the Irish coast.",
    available: true,
    featured: true,
  },
  {
    id: "52",
    title: "Ocean Memories",
    artistId: "19",
    artistName: "Lena Vogel",
    year: 2022,
    medium: "Sound and light installation",
    dimensions: { width: 144, height: 144, unit: "in" },
    price: 9500,
    currency: "€",
    imageUrl: "/images/artworks/ocean-memories.jpg",
    description: "Immersive installation recreating underwater soundscapes.",
    available: true,
    featured: false,
  },
  {
    id: "53",
    title: "Community Garden",
    artistId: "20",
    artistName: "Rafael Silva",
    year: 2023,
    medium: "Mural on community wall",
    dimensions: { width: 180, height: 120, unit: "in" },
    price: 8500,
    currency: "€",
    imageUrl: "/images/artworks/community-garden.jpg",
    description:
      "Vibrant mural celebrating urban agriculture and community spaces.",
    available: false,
    featured: true,
  },
  {
    id: "54",
    title: "Porcelain Forest",
    artistId: "21",
    artistName: "Chloe Dubois",
    year: 2022,
    medium: "Porcelain installation",
    dimensions: { width: 84, height: 60, unit: "in" },
    price: 6800,
    currency: "€",
    imageUrl: "/images/artworks/porcelain-forest.jpg",
    description: "Delicate porcelain forms creating an enchanted forest scene.",
    available: true,
    featured: false,
  },
  {
    id: "55",
    title: "AI Portraits",
    artistId: "22",
    artistName: "David Park",
    year: 2023,
    medium: "Generative AI art",
    dimensions: { width: 3840, height: 2160, unit: "px" },
    price: 3200,
    currency: "€",
    imageUrl: "/images/artworks/ai-portraits.jpg",
    description:
      "Series of portraits generated and curated using artificial intelligence.",
    available: true,
    featured: true,
  },
  {
    id: "56",
    title: "Third Culture",
    artistId: "23",
    artistName: "Maya Singh",
    year: 2022,
    medium: "Video and mixed media",
    dimensions: { width: 108, height: 72, unit: "in" },
    price: 5200,
    currency: "€",
    imageUrl: "/images/artworks/third-culture.jpg",
    description:
      "Installation exploring the experience of growing up between cultures.",
    available: true,
    featured: false,
  },
  {
    id: "57",
    title: "Iron Will",
    artistId: "24",
    artistName: "Viktor Ivanov",
    year: 2023,
    medium: "Forged iron sculpture",
    dimensions: { width: 96, height: 72, unit: "in" },
    price: 12800,
    currency: "€",
    imageUrl: "/images/artworks/iron-will.jpg",
    description:
      "Massive forged iron sculpture symbolizing strength and endurance.",
    available: true,
    featured: true,
  },
  {
    id: "58",
    title: "Evolving Landscape",
    artistId: "25",
    artistName: "Sophie Williams",
    year: 2023,
    medium: "Living installation",
    dimensions: { width: 144, height: 96, unit: "in" },
    price: 4200,
    currency: "€",
    imageUrl: "/images/artworks/evolving-landscape.jpg",
    description: "Living artwork that grows and changes with the seasons.",
    available: true,
    featured: false,
  },
  {
    id: "59",
    title: "Shadow and Light",
    artistId: "26",
    artistName: "Kenji Yamamoto",
    year: 2023,
    medium: "Light and shadow installation",
    dimensions: { width: 120, height: 120, unit: "in" },
    price: 7800,
    currency: "€",
    imageUrl: "/images/artworks/shadow-and-light.jpg",
    description:
      "Installation exploring the interplay between light and shadow.",
    available: true,
    featured: true,
  },
  {
    id: "60",
    title: "Navigators",
    artistId: "27",
    artistName: "Ana Costa",
    year: 2022,
    medium: "Oil on canvas",
    dimensions: { width: 60, height: 48, unit: "in" },
    price: 4500,
    currency: "€",
    imageUrl: "/images/artworks/navigators.jpg",
    description: "Historical seascape depicting Portuguese explorers.",
    available: true,
    featured: false,
  },
  {
    id: "61",
    title: "Sacred Text",
    artistId: "28",
    artistName: "Mohammed Al-Farsi",
    year: 2023,
    medium: "Gold leaf and ink on panel",
    dimensions: { width: 48, height: 36, unit: "in" },
    price: 5800,
    currency: "€",
    imageUrl: "/images/artworks/sacred-text.jpg",
    description:
      "Calligraphic work incorporating sacred texts with contemporary abstraction.",
    available: true,
    featured: true,
  },
  {
    id: "62",
    title: "Mythical Creatures",
    artistId: "29",
    artistName: "Elena Popescu",
    year: 2023,
    medium: "Layered paper art",
    dimensions: { width: 42, height: 30, unit: "in" },
    price: 3200,
    currency: "€",
    imageUrl: "/images/artworks/mythical-creatures.jpg",
    description:
      "Three-dimensional paper cut artwork depicting Romanian mythical creatures.",
    available: true,
    featured: false,
  },
  {
    id: "63",
    title: "Filtered Reality",
    artistId: "30",
    artistName: "Benjamin Taylor",
    year: 2022,
    medium: "Oil and digital print",
    dimensions: { width: 48, height: 36, unit: "in" },
    price: 3800,
    currency: "€",
    imageUrl: "/images/artworks/filtered-reality.jpg",
    description:
      "Portrait exploring how social media filters alter self-perception.",
    available: true,
    featured: true,
  },
  {
    id: "64",
    title: "Urban Jungle",
    artistId: "3",
    artistName: "Marcus Weber",
    year: 2023,
    medium: "Photomontage",
    dimensions: { width: 40, height: 30, unit: "in" },
    price: 2800,
    currency: "€",
    imageUrl: "/images/artworks/urban-jungle.jpg",
    description:
      "Photographic montage blending urban architecture with natural elements.",
    available: true,
    featured: false,
  },
  {
    id: "65",
    title: "Silent Strength",
    artistId: "4",
    artistName: "Sofia Ramirez",
    year: 2023,
    medium: "Oil on canvas",
    dimensions: { width: 36, height: 48, unit: "in" },
    price: 3200,
    currency: "€",
    imageUrl: "/images/artworks/silent-strength.jpg",
    description: "Portrait capturing quiet resilience and inner strength.",
    available: true,
    featured: true,
  },
  {
    id: "66",
    title: "Zen Flow",
    artistId: "5",
    artistName: "Yuki Tanaka",
    year: 2022,
    medium: "Ink on rice paper",
    dimensions: { width: 24, height: 36, unit: "in" },
    price: 1800,
    currency: "€",
    imageUrl: "/images/artworks/zen-flow.jpg",
    description: "Fluid ink work capturing the essence of Zen mindfulness.",
    available: true,
    featured: false,
  },
  {
    id: "67",
    title: "Ancestral Voices",
    artistId: "6",
    artistName: "Kwame Asante",
    year: 2022,
    medium: "Acrylic and collage on canvas",
    dimensions: { width: 60, height: 72, unit: "in" },
    price: 6800,
    currency: "€",
    imageUrl: "/images/artworks/ancestral-voices.jpg",
    description:
      "Mixed media work incorporating family photographs and documents.",
    available: false,
    featured: true,
  },
  {
    id: "68",
    title: "Rusted Memories",
    artistId: "7",
    artistName: "Isabella Rossi",
    year: 2023,
    medium: "Rusted steel and glass",
    dimensions: { width: 48, height: 60, unit: "in" },
    price: 5800,
    currency: "€",
    imageUrl: "/images/artworks/rusted-memories.jpg",
    description:
      "Sculpture exploring memory and decay through industrial materials.",
    available: true,
    featured: false,
  },
  {
    id: "69",
    title: "Vanishing Ice",
    artistId: "8",
    artistName: "Lars Jensen",
    year: 2023,
    medium: "Photographic triptych",
    dimensions: { width: 90, height: 30, unit: "in" },
    price: 4800,
    currency: "€",
    imageUrl: "/images/artworks/vanishing-ice.jpg",
    description: "Three-part photographic series documenting glacial retreat.",
    available: true,
    featured: true,
  },
  {
    id: "70",
    title: "Algorithmic Patterns",
    artistId: "9",
    artistName: "Aisha Hassan",
    year: 2023,
    medium: "Algorithmic digital art",
    dimensions: { width: 48, height: 48, unit: "in" },
    price: 3800,
    currency: "€",
    imageUrl: "/images/artworks/algorithmic-patterns.jpg",
    description:
      "Digital artwork generated using algorithms based on Islamic geometry.",
    available: true,
    featured: false,
  },
  {
    id: "71",
    title: "Rainforest Rhythms",
    artistId: "10",
    artistName: "Mateo Cruz",
    year: 2022,
    medium: "Sound and visual installation",
    dimensions: { width: 96, height: 72, unit: "in" },
    price: 5200,
    currency: "€",
    imageUrl: "/images/artworks/rainforest-rhythms.jpg",
    description:
      "Multi-sensory installation recreating Amazon rainforest atmosphere.",
    available: true,
    featured: true,
  },
  {
    id: "72",
    title: "Winter's Tale",
    artistId: "11",
    artistName: "Nina Petrova",
    year: 2023,
    medium: "Oil on canvas",
    dimensions: { width: 84, height: 60, unit: "in" },
    price: 14200,
    currency: "€",
    imageUrl: "/images/artworks/winters-tale.jpg",
    description: "Historical winter scene depicting traditional Russian life.",
    available: true,
    featured: false,
  },
  {
    id: "73",
    title: "Virtual Zen",
    artistId: "12",
    artistName: "Kaito Nakamura",
    year: 2022,
    medium: "VR experience",
    dimensions: { width: 360, height: 360, unit: "degree" },
    price: 4200,
    currency: "€",
    imageUrl: "/images/artworks/virtual-zen.jpg",
    description: "Virtual reality meditation experience based on Zen gardens.",
    available: true,
    featured: true,
  },
  {
    id: "74",
    title: "Desert Light",
    artistId: "13",
    artistName: "Fatima Al-Mansoori",
    year: 2023,
    medium: "Glass and natural light",
    dimensions: { width: 36, height: 48, unit: "in" },
    price: 4800,
    currency: "€",
    imageUrl: "/images/artworks/desert-light.jpg",
    description: "Glass sculpture that captures and refracts desert sunlight.",
    available: true,
    featured: false,
  },
  {
    id: "75",
    title: "Quantum Motion",
    artistId: "14",
    artistName: "Oliver Schmidt",
    year: 2023,
    medium: "Kinetic light sculpture",
    dimensions: { width: 108, height: 108, unit: "in" },
    price: 19800,
    currency: "€",
    imageUrl: "/images/artworks/quantum-motion.jpg",
    description: "Complex kinetic sculpture inspired by quantum mechanics.",
    available: false,
    featured: true,
  },
  {
    id: "76",
    title: "Sari Stories",
    artistId: "15",
    artistName: "Priya Sharma",
    year: 2023,
    medium: "Embroidered silk saris",
    dimensions: { width: 72, height: 48, unit: "in" },
    price: 5800,
    currency: "€",
    imageUrl: "/images/artworks/sari-stories.jpg",
    description:
      "Series of traditional saris embroidered with contemporary narratives.",
    available: true,
    featured: false,
  },
  {
    id: "77",
    title: "Café Culture",
    artistId: "16",
    artistName: "Carlos Mendez",
    year: 2023,
    medium: "Oil on canvas",
    dimensions: { width: 40, height: 30, unit: "in" },
    price: 3800,
    currency: "€",
    imageUrl: "/images/artworks/cafe-culture.jpg",
    description: "Vibrant scene of Buenos Aires café culture and conversation.",
    available: true,
    featured: true,
  },
  {
    id: "78",
    title: "Persian Gardens",
    artistId: "17",
    artistName: "Zahra Bahrami",
    year: 2022,
    medium: "Miniature on ivory",
    dimensions: { width: 4, height: 6, unit: "in" },
    price: 3200,
    currency: "€",
    imageUrl: "/images/artworks/persian-gardens.jpg",
    description:
      "Exquisite miniature depicting traditional Persian garden design.",
    available: true,
    featured: false,
  },
  {
    id: "79",
    title: "Wild Atlantic",
    artistId: "18",
    artistName: "Thomas O'Connell",
    year: 2023,
    medium: "Oil on canvas",
    dimensions: { width: 60, height: 48, unit: "in" },
    price: 5200,
    currency: "€",
    imageUrl: "/images/artworks/wild-atlantic.jpg",
    description: "Powerful seascape capturing the untamed Atlantic Ocean.",
    available: true,
    featured: true,
  },
  {
    id: "80",
    title: "Digital Nature",
    artistId: "19",
    artistName: "Lena Vogel",
    year: 2023,
    medium: "Interactive sound installation",
    dimensions: { width: 180, height: 180, unit: "in" },
    price: 12500,
    currency: "€",
    imageUrl: "/images/artworks/digital-nature.jpg",
    description:
      "Interactive installation where viewers' movements create natural soundscapes.",
    available: true,
    featured: false,
  },
];

// Utility functions remain the same
export const getArtistById = (id: string): Artist | undefined => {
  return artists.find((artist) => artist.id === id);
};

export const getArtworkById = (id: string): Artwork | undefined => {
  return artworks.find((artwork) => artwork.id === id);
};

export const getArtworksByArtist = (artistId: string): Artwork[] => {
  return artworks.filter((artwork) => artwork.artistId === artistId);
};

export const getFeaturedArtworks = (): Artwork[] => {
  return artworks.filter((artwork) => artwork.featured);
};

export const getFeaturedArtists = (): Artist[] => {
  return artists.filter((artist) => artist.featured);
};

export const paginateItems = <T>(
  items: T[],
  page: number,
  perPage: number = 16
): T[] => {
  const start = (page - 1) * perPage;
  const end = start + perPage;
  return items.slice(start, end);
};

export const getTotalPages = (
  totalItems: number,
  perPage: number = 16
): number => {
  return Math.ceil(totalItems / perPage);
};
